apiVersion: v1
kind: Service
metadata:
  name: ucd-server
  labels:
    app: {{ template "ucds.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ucds.service.type }} #NodePort
  ports:
    - name: {{ .Values.ucds.service.httpExternalName }}
      port: {{ .Values.ucds.service.httpExternalPort }}
      targetPort: {{ .Values.ucds.service.httpInternalPort }}
      protocol: TCP
    - name: {{ .Values.ucds.service.httpsExternalName }}
      port: {{ .Values.ucds.service.httpsExternalPort }}
      targetPort: {{ .Values.ucds.service.httpsInternalPort }}
      protocol: TCP
    - name: {{ .Values.ucds.service.jmsExternalName }}
      port: {{ .Values.ucds.service.jmsExternalPort }}
      targetPort: {{ .Values.ucds.service.jmspInternalPort }}
      protocol: TCP
  selector:
    app: {{ template "ucds.fullname" . }}
    release: {{ .Release.Name }}
