# Default values for chart1.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# UCD Server
ucds:
  name: ucds
  replicaCount: 1
  image:
    repository: ibmcom/ucds
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: ucd-server
    type: NodePort
    
    httpExternalName: http
    httpExternalPort: 8080
    httpInternalPort: 8080
    
    httpsExternalName: https
    httpsExternalPort: 8443
    httpsInternalPort: 8443
    
    jmsExternalName: jms
    jmsExternalPort: 7918
    jmsInternalPort: 7918
    
  monitoring: false
  resources:
    limits:
      cpu: 1
      memory: 2Gi
    requests:
      cpu: 1
      memory: 128Mi

# UCD Agent
ucda:
  name: ucda
  replicaCount: 2
  image:
    repository: ibmcom/ucda
    tag: latest
    pullPolicy: IfNotPresent

ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - chart-example.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
